apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: Helm
  name: {{ include "image-upload-frontend.frontend.fullname" . }}
  labels:
    {{- include "image-upload-frontend.frontend.labels" . | nindent 4 }}
spec:
  lookupPolicy:
    local: false
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: "{{.Values.frontend.image.repository}}:{{.Values.frontend.image.tag}}"
    importPolicy:
      importMode: Legacy
    name: {{.Values.frontend.image.tag}}
    referencePolicy:
      type: Source
