apiVersion: v1
kind: Service
metadata:
  name: {{ include "image-upload-frontend.frontend.fullname" . }}
  labels:
    {{- include "image-upload-frontend.frontend.labels" . | nindent 4 }}
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: 80
      targetPort: {{ .Values.frontend.service.port }}
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ .Values.frontend.name }}
    app.kubernetes.io/instance: {{ .Release.Name }} 
